### ISSUE TITLE
Vendor name and ID?

### ISSUE THREAD

**Issue by bryanbartow** [hankinsoft/AppWage#1]
What values are expected to be entered here when setting up a new account?

**Comment by tobihagemann** [comment]
Found it! https://reportingitc2.apple.com/reports.html

**Comment by hankinsoft** [comment]
Thats correct, first log into iTunes connect (https://itunesconnect.apple.com/) then navigate to https://reportingitc2.apple.com/reports.html. You may need to dropdown the 'All Vendors' dropdown to see your vendorId.

Vendor name can be whatever you want.

**Comment by hankinsoft** [comment]
I've just pushed new code to fix the load vendor details button. Once you fill out your username and password these should now load properly.
