### ISSUE TITLE
Multiple accounts not working

### ISSUE THREAD

**Issue by alexbrie** [hankinsoft/AppWage#13]
Although the UI allows to add multiple itunes accounts, only the reports for the first one seem to be retrieved.

**Comment by ddaddy** [comment]
Are they completely separate accounts or accounts that have previous merged?

I have an account that changed from personal to business, and therefore has 2 different vendor ID's.
When I added them both and imported old reports, I noticed that the apps that existed on both ID's only show under 1 account yet it contains all the data going back to the previous account.

**Comment by alexbrie** [comment]
my issue is with two completely separated accounts

**Comment by ddaddy** [comment]
Ok, was just a thought.

**Comment by hankinsoft** [comment]
Hi, Can you check your logs 'View' -> 'Logs' and see if their are any errors reported?

**Comment by alexbrie** [comment]
damn, you are right, it says something about 2-factor auth

**Comment by hankinsoft** [comment]
Unfortunately two factor auth is not available in AppWage. You will need to setup an application specific password. I believe https://github.com/hankinsoft/AppWage/issues/4 has some details on this.

**Comment by alexbrie** [comment]
I've disabled 2fact auth for now. Great idea to have app-specific passwd
