### ISSUE TITLE
Load on startup

### ISSUE THREAD

**Issue by ddaddy** [hankinsoft/AppWage#15]
The Load on startup doesn't seem to work.
Whenever I tick it and save then reopen preferences it is unticked again.

**Comment by hankinsoft** [comment]
I could never get load on startup working properly. I thought I had removed all of the code + preference, but I guess I missed some of the UI.

**Comment by hankinsoft** [comment]
FYI, I would suggest using Macs built in launch on startup option. I'll be removing this checkbox from the UI completely.
