### ISSUE TITLE
not working with two-factor authentication

### ISSUE THREAD

**Issue by mbinkhorst** [hankinsoft/AppWage#20]
Is it possible to make this app work with application specific passwords so I can keep two-factor authentication enabled on my accounts?

----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
    <Code>219</Code>
    <Message>Your Apple ID uses two-step verification or two-factor authentication. To use your Apple ID with Reporter, please create an app-specific password at appleid.apple.com.</Message>
</Error>
2016/12/11 11:30:01:149  ITCE: Failed to download weekly report

**Comment by hankinsoft** [comment]
Please see this issue: https://github.com/hankinsoft/AppWage/issues/4
