### ISSUE TITLE
The currency label is wrong

### ISSUE THREAD

**Issue by cyberbars** [hankinsoft/AppWage#21]
<img width="1025" alt="screen shot 2016-12-12 at 20 18 34" src="https://cloud.githubusercontent.com/assets/17948950/21109025/50c40a30-c0a8-11e6-8d43-ee48bbf916fa.png">

<img width="353" alt="screen shot 2016-12-12 at 20 23 21" src="https://cloud.githubusercontent.com/assets/17948950/21109166/e6aaba80-c0a8-11e6-928d-bc0f56a074db.png">

Current selected currency is USD. The main window graphs and stats shows correct USD numbers but the labels are RUB instead of USD.

**Comment by hankinsoft** [comment]
I'm not sure what you are saying. Could you please provide screenshots?

**Comment by cyberbars** [comment]
Seems to be the currency labels are configured by  [currencyFormatter setNumberStyle:NSNumberFormatterCurrencyStyle]; The NSNumberFormatterCurrencyStyle is using current system locale settings. Mine locale is set to russian, that why i see USD data labeled as RUBles.

**Comment by hankinsoft** [comment]
Ah, I understand. It will be a bit before I am able to look into this.
