### ISSUE TITLE
AppWage stopped collecting reports on March 22nd

### ISSUE THREAD

**Issue by eboehnisch** [hankinsoft/AppWage#27]
AppWage has stopped showing new sales data since March 22nd, 2017. I have tried to delete my account data and re-enter it but the newly collected data also stopped on the 22nd. Is this a known issue due to changes in iTunes Connect?

**Comment by hankinsoft** [comment]
Hi,
Hmm, no there is no known issue around this. If you try to collect reports,
then hit View -> Logs, open the latest log file, are there any errors?

**Comment by eboehnisch** [comment]
OK, found the problem: I activated two-factor authentication a while ago and now I need to use an app-specific password. Maybe AppWage should show this as an error message instead of only logging it.
