### ISSUE TITLE
report username/password replaced by access token

### ISSUE THREAD

**Issue by berbie** [hankinsoft/AppWage#29]
As of July 19 2017 the reporter api requires an access token and is no longer accessible vial username and password. An iTunes Connect access token can be generated in iTunes Connect > Sales & Trends > Reports > About Reports.
Note that the key in the postDictionary in AWiTunesConnectHelper.m:40 is "accesstoken". I patched my local version to use the password as its source but the UI should be updated. Also note that an iTunes Connect access token expires after 180 days.

**Comment by Sun3** [comment]
Mine has also stopped getting reports 3 days ago.
