### ISSUE TITLE
Reports in wrong folder

### ISSUE THREAD

**Issue by ddaddy** [hankinsoft/AppWage#3]
I'm not sure if this matters with regard to the functioning of the app, but when viewing the downloaded reports, I have 2x accounts setup and some reports are in the folder for the wrong account.

Shall I manually move them to the correct folder or are they not needed once downloaded?

**Comment by hankinsoft** [comment]
Hmmm, only some of the reports are in the wrong folder? Could I possible get a screenshot of finder showing exactly what you are seeing? Is there any chance you had an old old version of AppWage at anytime which may have created some older files?

**Comment by ddaddy** [comment]
Here's some screenshots showing the 8's & 9's mixed up.
I did used to use the version you had up on Github, but looking at the dates of some of these, they are quite recent, like 21st July that was downloaded today.

<img width="849" alt="Screenshot 2024-07-23 at 19 47 19" src="https://github.com/user-attachments/assets/c1a8230c-344a-46be-8669-c0f2e81daca9">
<img width="834" alt="Screenshot 2024-07-23 at 19 47 35" src="https://github.com/user-attachments/assets/29994e82-2ae4-48f7-89f2-c61916b0d355">
<img width="840" alt="Screenshot 2024-07-23 at 19 47 51" src="https://github.com/user-attachments/assets/5a69cd56-171e-449f-a04c-bfddb3720e6d">
<img width="788" alt="Screenshot 2024-07-23 at 19 48 20" src="https://github.com/user-attachments/assets/3081c406-fd2f-4777-a7b2-707679c42c64">
<img width="768" alt="Screenshot 2024-07-23 at 19 48 45" src="https://github.com/user-attachments/assets/e8620375-7348-4de2-8ff6-8529478f77c3">

**Comment by hankinsoft** [comment]
Ahhh, got it. I see whats going on. Getting it fixed, then I will have the new version into the store. Should be available by the end of the week.

**Comment by ddaddy** [comment]
Great. Happy to help.
Is there anything i need to do to tidy this up, or does it not really matter?

**Comment by hankinsoft** [comment]
Hi,
You can manually move the files if you want, but they are there more as a backup. App Store Connect only lets you download the last 365 days at a 'daily' level. After that they get lumped into weekly, monthly, yearly, etc, so some details are lost. They are only there should you need to re-import them in the future.

FYI the fixed build is submitted and should be available within a day or two depending on review time.

**Comment by hankinsoft** [comment]
Closing as this was sorted via email.
