### ISSUE TITLE
Latest version is 1.0.100 but my installed version is 1.0.101

### ISSUE THREAD

**Issue by Sun3** [hankinsoft/AppWage#32]
I just downloaded the latest git version in order to fix the reports not downloading but I noticed that the version from git is 1.0.100 but my current installed version is 1.0.101 (from AppWage.com site). I also do not see the token field.

Am I doing something wrong... any help is appreciated.

Thank you.

**Comment by Elwisz** [comment]
You're doing nothing wrong. I forgot to change the settings UI to show the token field, sorry.

**Comment by Sun3** [comment]
:) Sounds good. Thanks.

**Comment by Sun3** [comment]
Works great, thanks...
