### ISSUE TITLE
Emails aren't sending

### ISSUE THREAD

**Issue by kitefaster** [hankinsoft/AppWage#35]
Daily emails aren't being sent.

When I go to Preferences, Send test email it says "You must define CHILKAT_EMAIL_KEY to enable emails."

In the logs it says:
2017/08/04 08:43:24:039  Sending daily email.
2017/08/04 08:43:24:039  Failed to send daily email. Error: You must define CHILKAT_EMAIL_KEY to enable emails..

version 1.0.102 (605)

**Comment by hankinsoft** [comment]
Sorry about that, I forgot to add the API key when I compiled for the
website. Unfortunately I am away until Tuesday, but I will push a fix then.

**Comment by hankinsoft** [comment]
Hi,
I've just pushed a new build which should resolve sending emails: http://appwage.com/download.php. Gmail users note that you will currently need the enable sending emails from less secure environments as I have not added further support.

**Comment by kitefaster** [comment]
Thanks!

**Comment by kitefaster** [comment]
Actually only the test email from preferences is working.  The daily email doesn't send.  Logs state:

> Error sending email:Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo={NSLocalizedDescription=A stable connection to the server could not be established., MCOSMTPResponseKey=}
> 2017/09/18 09:33:44:603  Failed to send daily email. Error: A stable connection to the server could not be established..

**Comment by hankinsoft** [comment]
Hi Again,
Sorry for the delay! I've just released a new version which should sort this (the TLS option was not saving correctly). The latest version is available at: https://www.appwage.com/downloads/AppWage.1.0.105.app.zip

I've been using it for a couple weeks now with daily emails each day. If you get the chance, please let me know if that sorts things out.

**Comment by kitefaster** [comment]
Works now 2 days in a row.  Awesome!
