### ISSUE TITLE
App unable to connect to iTunes Connect

### ISSUE THREAD

**Issue by EdGonzalez-** [hankinsoft/AppWage#36]
Since 8/9/2017 the app has been unable to load revenue from iTunes Connect.  I tried re-entering the account credentials in Preferences, but it will not load the vendor details.

**Comment by dafi** [comment]
I suppose you have downloaded the new version 1.0.102 and most important you are using the [report token](https://help.apple.com/itc/appsreporterguide/?lang=en#/apd2f1f1cfa3)

You must enter the token on the Preferences dialog under the Account tab

**Comment by welsonla** [comment]
@dafi It works， thx
