### ISSUE TITLE
Support for two-factor auth

### ISSUE THREAD

**Issue by jksk** [hankinsoft/AppWage#4]
I have two accounts, one of which is two-factor auth enabled. For this one, no data is downloaded.

**Comment by BeauNouvelle** [comment]
Two factor auth user here too.

**Comment by arnoappenzeller** [comment]
It works with an app specific password you can create on:

https://appleid.apple.com

Maybe there should be a warning that asks for this when the validation failes

**Comment by CPDigitalDarkroom** [comment]
> It works with an app specific password...

TIL those are a thing.

**Comment by jksk** [comment]
@arnoappenzeller Works great, thanks for the info.
