### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by ddaddy** [hankinsoft/AppWage#4]
I have 1 day of sales missing: 20th July 2024
I've manually downloaded the report from ASC but when I try to import it, it just hangs on `Preparing for import`.

I've tried importing both the `.txt` and `.txt.gz` files with the same result. I have to force quit the app.

I'm wondering if there's something odd you're not parsing from this report which is why it hasn't downloaded it itself.

I'm happy to privately share a copy of the sales report if you need it.

**Comment by hankinsoft** [comment]
Hi,
Could you possible email the file to kyle @ hankinsoft.com? Also, could you try the import first, then go to 'View' -> 'Logs' and provide the log file as well?

**Comment by ddaddy** [comment]
Logs when importing `.txt`:

```
2024/07/27 08:39:52:952  onImportSalesReports: 2
2024/07/27 08:39:53:460  Window will begin sheet
2024/07/27 08:39:56:568  Dragging enetered
2024/07/27 08:39:59:744  Window ended sheet.
2024/07/27 08:39:59:751  Window will begin sheet
2024/07/27 08:40:06:890  User wants to open logs (23 - 2024.23). Path is: /Users/<Redacted>
```

When I try with the `.txt.gz` it doesn't have that last line.

Logs emailed.

**Comment by hankinsoft** [comment]
Closing as this was sorted via email.
