### ISSUE TITLE
GZIP needs fixing

### ISSUE THREAD

**Issue by ddaddy** [hankinsoft/AppWage#42]
Since Dec 12th, all reports downloaded are empty. The same issue occurred in an iOS app I use.
The problem was with the gzip module. I'm not sure if Apple have updated something their end, but updating/replacing the gzip module fixed it in the iOS app I use.

I've downloaded this source to try and fix it, but i'm afraid it would take me too long to get my head around the current code (And i've never used Pods, which I believe you do for GZIP).

**Comment by hankinsoft** [comment]
Thanks for the report! It will be awhile before I get to look into it (not
something I can provide an eta on). Per usually pull requests are welcome,
should anyone wish to look into it.

Cheers,
Kyle

**Comment by ddaddy** [comment]
Something very odd just happened. I just got a report through for yesterday (19th Dec 18).
I've tried to make it re-download the empty ones but they are still empty, so for now I have manually imported the missing days.

I wonder what Apple could have changed that allowed yesterdays to download but not the others.
